# Generated by Django 4.0.1 on 2022-04-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('emp_no', models.IntegerField(primary_key=True, serialize=False, verbose_name='employee number')),
                ('first_name', models.CharField(max_length=14, verbose_name='first name')),
                ('last_name', models.CharField(max_length=16, verbose_name='last name')),
                ('gender', models.CharField(max_length=1, verbose_name='gender')),
                ('birth_date', models.DateField(verbose_name='birthday')),
                ('address', models.TextField(verbose_name='address')),
                ('hire_date', models.DateField(verbose_name='hire date')),
            ],
        ),
    ]
